CREATE TABLE IF NOT EXISTS listings (
    listing_id        VARCHAR(36) PRIMARY KEY,
    seller_id         VARCHAR(36) NOT NULL,
    description       TEXT,
    posted_at         TIMESTAMP NOT NULL DEFAULT now(),
    status            VARCHAR(20),
    deal_type         VARCHAR(20),
    price             NUMERIC(12,2),
    car_id            VARCHAR(36),
    mileage           INTEGER,
    owners_count      INTEGER,
    accidents_count   INTEGER,
    condition         VARCHAR(50),
    color             VARCHAR(30),
    config_id         VARCHAR(36),
    engine_type       VARCHAR(50),
    engine_volume     VARCHAR(50),
    engine_power      INTEGER,
    cylinders         INTEGER,
    transmission      VARCHAR(20),
    drivetrain        VARCHAR(20),
    model_id          VARCHAR(36),
    model_name        VARCHAR(50),
    make              VARCHAR(50),
    year              INTEGER,
    body_type         VARCHAR(30),
    generation        VARCHAR(50),
    weight_kg         NUMERIC(8,2),
    seller_name       VARCHAR(100),
    seller_rating     NUMERIC(3,2),
    seller_sales_count INTEGER,
    seller_is_business BOOLEAN,
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP NOT NULL DEFAULT now()
);